CREATE DATABASE form_data;
USE form_data;

CREATE TABLE submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  gender VARCHAR(10) NOT NULL,
  location VARCHAR(255) NOT NULL,
  pincode VARCHAR(10) NOT NULL,
  submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
